name: eQAITapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
 # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/nt_logo.png
    - assets/image/stc_logo.png
    - assets/image/user.png
    - assets/image/riyadh.png
    - assets/image/lock.png
    - assets/image/inspection.png
    - assets/image/fiber.png
    - assets/image/material-management.png
    - assets/image/surveyor.png
    - assets/image/settings.png

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/STC-Bold.ttf
        - asset: assets/fonts/STC-Light.ttf
        - asset: assets/fonts/STC-Regular.ttf
          weight: 700

